### ISSUE TITLE
An error has occured while executing Python code

### ISSUE THREAD

**Issue by slewuk** [3nids/postgres91plusauditor#6]
Hello. I am receiving the following error when using the postgres91plusauditor plugin. I am an amateur, so apologies if this isn't the correct place to post the error:

Traceback (most recent call last):
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\postgres91plusauditor.py", line 61, in audit
    self.auditDlg = AuditDialog(self.iface, layerId, featureId)
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\gui\auditdialog.py", line 61, in **init**
    self.loggedActionsTable = LoggedActionsTable(self.loggedActionsWidget)
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\gui\loggedactionstable.py", line 25, in **init**
    self.displayColumns()
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\gui\loggedactionstable.py", line 35, in displayColumns
    columns = self.settings.value("columns")
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\qgissettingmanager\settingmanager.py", line 65, in value
    return setting.getValue()
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\qgissettingmanager\setting.py", line 67, in getValue
    return self.getGlobal()
  File "C:\Users\shaunl/.qgis2/python/plugins\postgres91plusauditor\qgissettingmanager\types\stringlist.py", line 43, in 
    getGlobal = lambda: QSettings(pluginName, pluginName).value(name, defaultValue, type=list)
TypeError: unable to convert a QVariant of type 11 to a QMetaType of type 270

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.0.1-Dufour Dufour, 34139bc

**Comment by haubourg** [comment]
+1 same here with 2.10/master . Worked well, and that error is triggered each time I try to display logging window. It seems it appeared when clicking on the checkbox in the bottom left corner. Can not say more since I can't reopen it. 
Reinstalling, creating a new project, truncating audit table and dropping / readding triggers on table did nothing. 
Any idea?

my table structure: 

```
-- Table: qgiswork.rwbody

-- DROP TABLE qgiswork.rwbody;

CREATE TABLE qgiswork.rwbody
(
  eu_cd character varying(24) NOT NULL,
  version_dce character varying(10) NOT NULL,
  region_cd character varying(2),
  system character varying(1),
  alt_cat character varying(4),
  geol_cat character varying(1),
  size_cat character varying(2),
  lat real,
  lon real,
  geology character varying(254),
  critmdo character varying(1),
  ecor_eu character varying(2),
  hydroecor character varying(4),
  size real,
  type_fr character varying(16),
  strah_max character varying(2),
  strah_min character varying(2),
  tpme character varying(4),
  ctx_pisci character varying(1),
  ref_ibgn numeric(4,2),
  ref_ibd numeric(4,2),
  ref_ip numeric(4,2),
  ref_ibmr numeric(4,2),
  geoml93 geometry(LineString,2154),
  uid integer NOT NULL,
  CONSTRAINT rwbody_pkey PRIMARY KEY (uid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE qgiswork.rwbody
  OWNER TO pgadmin;

-- Index: qgiswork.rwbody_geoml93_1440087039887

-- DROP INDEX qgiswork.rwbody_geoml93_1440087039887;

CREATE INDEX rwbody_geoml93_1440087039887
  ON qgiswork.rwbody
  USING gist
  (geoml93);

-- Index: qgiswork.rwbody_type_fr_1440087039854

-- DROP INDEX qgiswork.rwbody_type_fr_1440087039854;

CREATE INDEX rwbody_type_fr_1440087039854
  ON qgiswork.rwbody
  USING btree
  (type_fr COLLATE pg_catalog."default");


-- Trigger: audit_trigger_row on qgiswork.rwbody

-- DROP TRIGGER audit_trigger_row ON qgiswork.rwbody;

CREATE TRIGGER audit_trigger_row
  AFTER INSERT OR UPDATE OR DELETE
  ON qgiswork.rwbody
  FOR EACH ROW
  EXECUTE PROCEDURE audit.if_modified_func('true');

-- Trigger: audit_trigger_stm on qgiswork.rwbody

-- DROP TRIGGER audit_trigger_stm ON qgiswork.rwbody;

CREATE TRIGGER audit_trigger_stm
  AFTER TRUNCATE
  ON qgiswork.rwbody
  FOR EACH STATEMENT
  EXECUTE PROCEDURE audit.if_modified_func('true');


```

**Comment by 3nids** [comment]
The plugin is deprecated and is not maintained anymore.
Sorry for the troubles.
Hopefuly a new solution should arise later this year.
