### ISSUE TITLE
JSON column type issue

### ISSUE THREAD

**Issue by nautoguide** [3nids/postgres91plusauditor#7]
The plugin fails if the feature table has columns of type JSON as these are not supported by QGIS and are ignored. Subsequently the plugin fails when attempting to display this column. 

I'd offer a fix, but am a python newbie ;-)

**Comment by 3nids** [comment]
The plugin is deprecated and is not maintained anymore.
Sorry for the troubles.
Hopefuly a new solution should arise later this year.
